VOICE_CONFIG = {
    "listen_seconds": 5,
    "wake_required": False,
    "confirm_commands": False,
    "voice_engine": "piper",
    "voice_profile": "lessac",
    "continuous_listening": True,
    "push_to_talk": False,
    "command_confirmation": False,
    "ignore_noise_phrases": [
        "waves crashing",
        "music",
        "noise",
        "background noise",
        "silence",
        "blank audio",
        "wind blowing",
        "wind howling",
        "crashing",
        "blowing",
        "howling",
        "ocean",
        "waves",
    ],
}
