from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/academic_support")
PHASE_CONFIGS = [{'phase': 1861, 'title': 'Distinction-level assignment assistant', 'name': 'distinction_level_assignment_assistant', 'filename': 'distinction_level_assignment_assistant.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'distinction-level-assignment-assistant'}, {'phase': 1862, 'title': 'Academic structure validator', 'name': 'academic_structure_validator', 'filename': 'academic_structure_validator.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'academic-structure-validator'}, {'phase': 1863, 'title': 'Harvard reference helper', 'name': 'harvard_reference_helper', 'filename': 'harvard_reference_helper.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'harvard-reference-helper'}, {'phase': 1864, 'title': 'Plagiarism-safe rewrite mode', 'name': 'plagiarism_safe_rewrite_mode', 'filename': 'plagiarism_safe_rewrite_mode.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'plagiarism-safe-rewrite-mode'}, {'phase': 1865, 'title': 'Research gap analyzer', 'name': 'research_gap_analyzer', 'filename': 'research_gap_analyzer.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'research-gap-analyzer'}, {'phase': 1866, 'title': 'Literature review matrix builder', 'name': 'literature_review_matrix_builder', 'filename': 'literature_review_matrix_builder.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'literature-review-matrix-builder'}, {'phase': 1867, 'title': 'Methodology advisor', 'name': 'methodology_advisor', 'filename': 'methodology_advisor.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'methodology-advisor'}, {'phase': 1868, 'title': 'Findings chapter assistant', 'name': 'findings_chapter_assistant', 'filename': 'findings_chapter_assistant.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'findings-chapter-assistant'}, {'phase': 1869, 'title': 'Presentation slide planner', 'name': 'presentation_slide_planner', 'filename': 'presentation_slide_planner.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'presentation-slide-planner'}, {'phase': 1870, 'title': 'Viva question simulator', 'name': 'viva_question_simulator', 'filename': 'viva_question_simulator.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'viva-question-simulator'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
