from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/access_remote_control")
PHASE_CONFIGS = [{'phase': 1781, 'title': 'Local account system', 'name': 'local_account_system', 'filename': 'local_account_system.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'local-account-system'}, {'phase': 1782, 'title': 'Role-based access inside JARVIS', 'name': 'role_based_access_inside_jarvis', 'filename': 'role_based_access_inside_jarvis.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'role-based-access-inside-jarvis'}, {'phase': 1783, 'title': 'Guest mode', 'name': 'guest_mode', 'filename': 'guest_mode.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'guest-mode'}, {'phase': 1784, 'title': 'Admin mode', 'name': 'admin_mode', 'filename': 'admin_mode.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'admin-mode'}, {'phase': 1785, 'title': 'Emergency lock mode', 'name': 'emergency_lock_mode', 'filename': 'emergency_lock_mode.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'emergency-lock-mode'}, {'phase': 1786, 'title': 'Device pairing flow', 'name': 'device_pairing_flow', 'filename': 'device_pairing_flow.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'device-pairing-flow'}, {'phase': 1787, 'title': 'Mobile web controller', 'name': 'mobile_web_controller', 'filename': 'mobile_web_controller.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'mobile-web-controller'}, {'phase': 1788, 'title': 'Secure tunnel dashboard', 'name': 'secure_tunnel_dashboard', 'filename': 'secure_tunnel_dashboard.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'secure-tunnel-dashboard'}, {'phase': 1789, 'title': 'API token manager', 'name': 'api_token_manager', 'filename': 'api_token_manager.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'api-token-manager'}, {'phase': 1790, 'title': 'Remote command approval', 'name': 'remote_command_approval', 'filename': 'remote_command_approval.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'remote-command-approval'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
