from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/agent_governance_expansion")
PHASE_CONFIGS = [{'phase': 1921, 'title': 'Agent performance reviews', 'name': 'agent_performance_reviews', 'filename': 'agent_performance_reviews.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'agent-performance-reviews'}, {'phase': 1922, 'title': 'Agent salary/cost simulator', 'name': 'agent_salary_cost_simulator', 'filename': 'agent_salary_cost_simulator.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'agent-salary-cost-simulator'}, {'phase': 1923, 'title': 'Agent task delegation board', 'name': 'agent_task_delegation_board', 'filename': 'agent_task_delegation_board.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'agent-task-delegation-board'}, {'phase': 1924, 'title': 'Agent accountability logs', 'name': 'agent_accountability_logs', 'filename': 'agent_accountability_logs.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'agent-accountability-logs'}, {'phase': 1925, 'title': 'Agent escalation paths', 'name': 'agent_escalation_paths', 'filename': 'agent_escalation_paths.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'agent-escalation-paths'}, {'phase': 1926, 'title': 'Agent collaboration protocol', 'name': 'agent_collaboration_protocol', 'filename': 'agent_collaboration_protocol.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'agent-collaboration-protocol'}, {'phase': 1927, 'title': 'Agent meeting room', 'name': 'agent_meeting_room', 'filename': 'agent_meeting_room.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'agent-meeting-room'}, {'phase': 1928, 'title': 'Agent memory separation', 'name': 'agent_memory_separation', 'filename': 'agent_memory_separation.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'agent-memory-separation'}, {'phase': 1929, 'title': 'Agent shared company knowledge', 'name': 'agent_shared_company_knowledge', 'filename': 'agent_shared_company_knowledge.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'agent-shared-company-knowledge'}, {'phase': 1930, 'title': 'Agent permission matrix', 'name': 'agent_permission_matrix', 'filename': 'agent_permission_matrix.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'agent-permission-matrix'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
