from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/agent_platform_productization")
PHASE_CONFIGS = [{'phase': 1931, 'title': 'Agent ethical constraints', 'name': 'agent_ethical_constraints', 'filename': 'agent_ethical_constraints.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'agent-ethical-constraints'}, {'phase': 1932, 'title': 'Agent shutdown hierarchy', 'name': 'agent_shutdown_hierarchy', 'filename': 'agent_shutdown_hierarchy.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'agent-shutdown-hierarchy'}, {'phase': 1933, 'title': 'Agent sandbox testing', 'name': 'agent_sandbox_testing', 'filename': 'agent_sandbox_testing.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'agent-sandbox-testing'}, {'phase': 1934, 'title': 'Agent promotion system', 'name': 'agent_promotion_system', 'filename': 'agent_promotion_system.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'agent-promotion-system'}, {'phase': 1935, 'title': 'Agent skill training academy', 'name': 'agent_skill_training_academy', 'filename': 'agent_skill_training_academy.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'agent-skill-training-academy'}, {'phase': 1936, 'title': 'Agent marketplace foundation', 'name': 'agent_marketplace_foundation', 'filename': 'agent_marketplace_foundation.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'agent-marketplace-foundation'}, {'phase': 1937, 'title': 'Client-specific agent instances', 'name': 'client_specific_agent_instances', 'filename': 'client_specific_agent_instances.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'client-specific-agent-instances'}, {'phase': 1938, 'title': 'White-label AI workforce product', 'name': 'white_label_ai_workforce_product', 'filename': 'white_label_ai_workforce_product.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'white-label-ai-workforce-product'}, {'phase': 1939, 'title': 'Sellable JARVIS platform', 'name': 'sellable_jarvis_platform', 'filename': 'sellable_jarvis_platform.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'sellable-jarvis-platform'}, {'phase': 1940, 'title': 'LKP AI automation suite', 'name': 'lkp_ai_automation_suite', 'filename': 'lkp_ai_automation_suite.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'lkp-ai-automation-suite'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
