from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/ai_workforce_roles")
PHASE_CONFIGS = [{'phase': 1901, 'title': 'Multi-agent company workforce', 'name': 'multi_agent_company_workforce', 'filename': 'multi_agent_company_workforce.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'multi-agent-company-workforce'}, {'phase': 1902, 'title': 'AI developer employee', 'name': 'ai_developer_employee', 'filename': 'ai_developer_employee.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'ai-developer-employee'}, {'phase': 1903, 'title': 'AI digital marketer employee', 'name': 'ai_digital_marketer_employee', 'filename': 'ai_digital_marketer_employee.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'ai-digital-marketer-employee'}, {'phase': 1904, 'title': 'AI SEO strategist employee', 'name': 'ai_seo_strategist_employee', 'filename': 'ai_seo_strategist_employee.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'ai-seo-strategist-employee'}, {'phase': 1905, 'title': 'AI accountant employee', 'name': 'ai_accountant_employee', 'filename': 'ai_accountant_employee.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'ai-accountant-employee'}, {'phase': 1906, 'title': 'AI support agent employee', 'name': 'ai_support_agent_employee', 'filename': 'ai_support_agent_employee.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'ai-support-agent-employee'}, {'phase': 1907, 'title': 'AI project manager employee', 'name': 'ai_project_manager_employee', 'filename': 'ai_project_manager_employee.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'ai-project-manager-employee'}, {'phase': 1908, 'title': 'AI content strategist employee', 'name': 'ai_content_strategist_employee', 'filename': 'ai_content_strategist_employee.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'ai-content-strategist-employee'}, {'phase': 1909, 'title': 'AI salesperson employee', 'name': 'ai_salesperson_employee', 'filename': 'ai_salesperson_employee.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'ai-salesperson-employee'}, {'phase': 1910, 'title': 'AI legal assistant employee', 'name': 'ai_legal_assistant_employee', 'filename': 'ai_legal_assistant_employee.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'ai-legal-assistant-employee'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
