from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/ai_workforce_operations")
PHASE_CONFIGS = [{'phase': 1911, 'title': 'AI HR assistant employee', 'name': 'ai_hr_assistant_employee', 'filename': 'ai_hr_assistant_employee.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'ai-hr-assistant-employee'}, {'phase': 1912, 'title': 'AI data analyst employee', 'name': 'ai_data_analyst_employee', 'filename': 'ai_data_analyst_employee.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'ai-data-analyst-employee'}, {'phase': 1913, 'title': 'AI QA engineer employee', 'name': 'ai_qa_engineer_employee', 'filename': 'ai_qa_engineer_employee.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'ai-qa-engineer-employee'}, {'phase': 1914, 'title': 'AI DevOps engineer employee', 'name': 'ai_devops_engineer_employee', 'filename': 'ai_devops_engineer_employee.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'ai-devops-engineer-employee'}, {'phase': 1915, 'title': 'AI UI/UX designer employee', 'name': 'ai_ui_ux_designer_employee', 'filename': 'ai_ui_ux_designer_employee.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'ai-ui-ux-designer-employee'}, {'phase': 1916, 'title': 'AI video editor employee', 'name': 'ai_video_editor_employee', 'filename': 'ai_video_editor_employee.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'ai-video-editor-employee'}, {'phase': 1917, 'title': 'AI brand manager employee', 'name': 'ai_brand_manager_employee', 'filename': 'ai_brand_manager_employee.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'ai-brand-manager-employee'}, {'phase': 1918, 'title': 'AI receptionist employee', 'name': 'ai_receptionist_employee', 'filename': 'ai_receptionist_employee.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'ai-receptionist-employee'}, {'phase': 1919, 'title': 'AI operations analyst employee', 'name': 'ai_operations_analyst_employee', 'filename': 'ai_operations_analyst_employee.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'ai-operations-analyst-employee'}, {'phase': 1920, 'title': 'AI executive assistant employee', 'name': 'ai_executive_assistant_employee', 'filename': 'ai_executive_assistant_employee.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'ai-executive-assistant-employee'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
