from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/artistic_storytelling")
PHASE_CONFIGS = [{'phase': 2331, 'title': 'Adaptive intuition framework', 'name': 'adaptive_intuition_framework', 'filename': 'adaptive_intuition_framework.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'adaptive-intuition-framework'}, {'phase': 2332, 'title': 'Autonomous imagination-coordination AI', 'name': 'autonomous_imagination_coordination_ai', 'filename': 'autonomous_imagination_coordination_ai.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'autonomous-imagination-coordination-ai'}, {'phase': 2333, 'title': 'Infinite-scale creativity harmonization engine', 'name': 'infinite_scale_creativity_harmonization_engine', 'filename': 'infinite_scale_creativity_harmonization_engine.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'infinite-scale-creativity-harmonization-engine'}, {'phase': 2334, 'title': 'Recursive inspiration framework', 'name': 'recursive_inspiration_framework', 'filename': 'recursive_inspiration_framework.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'recursive-inspiration-framework'}, {'phase': 2335, 'title': 'Universal artistic substrate', 'name': 'universal_artistic_substrate', 'filename': 'universal_artistic_substrate.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'universal-artistic-substrate'}, {'phase': 2336, 'title': 'Adaptive expression-coordination AI', 'name': 'adaptive_expression_coordination_ai', 'filename': 'adaptive_expression_coordination_ai.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'adaptive-expression-coordination-ai'}, {'phase': 2337, 'title': 'Autonomous narrative framework', 'name': 'autonomous_narrative_framework', 'filename': 'autonomous_narrative_framework.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'autonomous-narrative-framework'}, {'phase': 2338, 'title': 'Infinite-scale storytelling engine', 'name': 'infinite_scale_storytelling_engine', 'filename': 'infinite_scale_storytelling_engine.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'infinite-scale-storytelling-engine'}, {'phase': 2339, 'title': 'Recursive cinematic harmonization AI', 'name': 'recursive_cinematic_harmonization_ai', 'filename': 'recursive_cinematic_harmonization_ai.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'recursive-cinematic-harmonization-ai'}, {'phase': 2340, 'title': 'Universal entertainment substrate', 'name': 'universal_entertainment_substrate', 'filename': 'universal_entertainment_substrate.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'universal-entertainment-substrate'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
