from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/business_connector")
PHASE_CONFIGS = [{'phase': 1961, 'title': 'Instagram connector', 'name': 'instagram_connector', 'filename': 'instagram_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'instagram-connector'}, {'phase': 1962, 'title': 'LinkedIn connector', 'name': 'linkedin_connector', 'filename': 'linkedin_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'linkedin-connector'}, {'phase': 1963, 'title': 'X connector', 'name': 'x_connector', 'filename': 'x_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'x-connector'}, {'phase': 1964, 'title': 'YouTube connector', 'name': 'youtube_connector', 'filename': 'youtube_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'youtube-connector'}, {'phase': 1965, 'title': 'Google Business Profile connector', 'name': 'google_business_profile_connector', 'filename': 'google_business_profile_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'google-business-profile-connector'}, {'phase': 1966, 'title': 'WordPress connector', 'name': 'wordpress_connector', 'filename': 'wordpress_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'wordpress-connector'}, {'phase': 1967, 'title': 'Laravel app connector', 'name': 'laravel_app_connector', 'filename': 'laravel_app_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'laravel-app-connector'}, {'phase': 1968, 'title': 'Shopify/WooCommerce connector', 'name': 'shopify_woocommerce_connector', 'filename': 'shopify_woocommerce_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'shopify-woocommerce-connector'}, {'phase': 1969, 'title': 'Stripe/PayHere connector', 'name': 'stripe_payhere_connector', 'filename': 'stripe_payhere_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'stripe-payhere-connector'}, {'phase': 1970, 'title': 'Bank API connector', 'name': 'bank_api_connector', 'filename': 'bank_api_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'bank-api-connector'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
