from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/business_document")
PHASE_CONFIGS = [{'phase': 1871, 'title': 'Client document generator', 'name': 'client_document_generator', 'filename': 'client_document_generator.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'client-document-generator'}, {'phase': 1872, 'title': 'Contract template manager', 'name': 'contract_template_manager', 'filename': 'contract_template_manager.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'contract-template-manager'}, {'phase': 1873, 'title': 'Quotation template engine', 'name': 'quotation_template_engine', 'filename': 'quotation_template_engine.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'quotation-template-engine'}, {'phase': 1874, 'title': 'Invoice template engine', 'name': 'invoice_template_engine', 'filename': 'invoice_template_engine.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'invoice-template-engine'}, {'phase': 1875, 'title': 'Proposal design assistant', 'name': 'proposal_design_assistant', 'filename': 'proposal_design_assistant.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'proposal-design-assistant'}, {'phase': 1876, 'title': 'Company profile generator', 'name': 'company_profile_generator', 'filename': 'company_profile_generator.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'company-profile-generator'}, {'phase': 1877, 'title': 'Business plan generator', 'name': 'business_plan_generator', 'filename': 'business_plan_generator.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'business-plan-generator'}, {'phase': 1878, 'title': 'Pitch deck assistant', 'name': 'pitch_deck_assistant', 'filename': 'pitch_deck_assistant.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'pitch-deck-assistant'}, {'phase': 1879, 'title': 'Tender document compiler', 'name': 'tender_document_compiler', 'filename': 'tender_document_compiler.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'tender-document-compiler'}, {'phase': 1880, 'title': 'Legal notice draft assistant', 'name': 'legal_notice_draft_assistant', 'filename': 'legal_notice_draft_assistant.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'legal-notice-draft-assistant'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
