from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/connector_governance_platform")
PHASE_CONFIGS = [{'phase': 1991, 'title': 'Connector permission auditor', 'name': 'connector_permission_auditor', 'filename': 'connector_permission_auditor.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'connector-permission-auditor'}, {'phase': 1992, 'title': 'Connector health monitor', 'name': 'connector_health_monitor', 'filename': 'connector_health_monitor.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'connector-health-monitor'}, {'phase': 1993, 'title': 'Connector retry engine', 'name': 'connector_retry_engine', 'filename': 'connector_retry_engine.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'connector-retry-engine'}, {'phase': 1994, 'title': 'Connector usage billing', 'name': 'connector_usage_billing', 'filename': 'connector_usage_billing.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'connector-usage-billing'}, {'phase': 1995, 'title': 'Connector marketplace', 'name': 'connector_marketplace', 'filename': 'connector_marketplace.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'connector-marketplace'}, {'phase': 1996, 'title': 'Cross-connector workflow intelligence', 'name': 'cross_connector_workflow_intelligence', 'filename': 'cross_connector_workflow_intelligence.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'cross-connector-workflow-intelligence'}, {'phase': 1997, 'title': 'Universal business automation brain', 'name': 'universal_business_automation_brain', 'filename': 'universal_business_automation_brain.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'universal-business-automation-brain'}, {'phase': 1998, 'title': 'Autonomous company operating system', 'name': 'autonomous_company_operating_system', 'filename': 'autonomous_company_operating_system.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'autonomous-company-operating-system'}, {'phase': 1999, 'title': 'JARVIS Enterprise Product Core', 'name': 'jarvis_enterprise_product_core', 'filename': 'jarvis_enterprise_product_core.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'jarvis-enterprise-product-core'}, {'phase': 2000, 'title': 'JARVIS Sovereign Intelligence Platform', 'name': 'jarvis_sovereign_intelligence_platform', 'filename': 'jarvis_sovereign_intelligence_platform.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'jarvis-sovereign-intelligence-platform'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
