from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/design_system")
PHASE_CONFIGS = [{'phase': 1831, 'title': 'Design-to-code assistant', 'name': 'design_to_code_assistant', 'filename': 'design_to_code_assistant.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'design-to-code-assistant'}, {'phase': 1832, 'title': 'Figma interpretation bridge', 'name': 'figma_interpretation_bridge', 'filename': 'figma_interpretation_bridge.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'figma-interpretation-bridge'}, {'phase': 1833, 'title': 'Screenshot-to-Tailwind generator', 'name': 'screenshot_to_tailwind_generator', 'filename': 'screenshot_to_tailwind_generator.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'screenshot-to-tailwind-generator'}, {'phase': 1834, 'title': 'Component library builder', 'name': 'component_library_builder', 'filename': 'component_library_builder.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'component-library-builder'}, {'phase': 1835, 'title': 'Brand design-system guardian', 'name': 'brand_design_system_guardian', 'filename': 'brand_design_system_guardian.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'brand-design-system-guardian'}, {'phase': 1836, 'title': 'Logo usage compliance checker', 'name': 'logo_usage_compliance_checker', 'filename': 'logo_usage_compliance_checker.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'logo-usage-compliance-checker'}, {'phase': 1837, 'title': 'Color palette consistency checker', 'name': 'color_palette_consistency_checker', 'filename': 'color_palette_consistency_checker.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'color-palette-consistency-checker'}, {'phase': 1838, 'title': 'Typography consistency analyzer', 'name': 'typography_consistency_analyzer', 'filename': 'typography_consistency_analyzer.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'typography-consistency-analyzer'}, {'phase': 1839, 'title': 'Icon system manager', 'name': 'icon_system_manager', 'filename': 'icon_system_manager.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'icon-system-manager'}, {'phase': 1840, 'title': 'UI copywriting assistant', 'name': 'ui_copywriting_assistant', 'filename': 'ui_copywriting_assistant.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'ui-copywriting-assistant'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
