from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/desktop_interface")
PHASE_CONFIGS = [{'phase': 1771, 'title': 'Desktop UI command palette', 'name': 'desktop_ui_command_palette', 'filename': 'desktop_ui_command_palette.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'desktop-ui-command-palette'}, {'phase': 1772, 'title': 'Floating assistant widget', 'name': 'floating_assistant_widget', 'filename': 'floating_assistant_widget.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'floating-assistant-widget'}, {'phase': 1773, 'title': 'System tray quick actions', 'name': 'system_tray_quick_actions', 'filename': 'system_tray_quick_actions.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'system-tray-quick-actions'}, {'phase': 1774, 'title': 'Project health dashboard', 'name': 'project_health_dashboard', 'filename': 'project_health_dashboard.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'project-health-dashboard'}, {'phase': 1775, 'title': 'Memory browser interface', 'name': 'memory_browser_interface', 'filename': 'memory_browser_interface.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'memory-browser-interface'}, {'phase': 1776, 'title': 'Task board UI', 'name': 'task_board_ui', 'filename': 'task_board_ui.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'task-board-ui'}, {'phase': 1777, 'title': 'Agent activity timeline', 'name': 'agent_activity_timeline', 'filename': 'agent_activity_timeline.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'agent-activity-timeline'}, {'phase': 1778, 'title': 'Approval inbox', 'name': 'approval_inbox', 'filename': 'approval_inbox.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'approval-inbox'}, {'phase': 1779, 'title': 'Notification center', 'name': 'notification_center', 'filename': 'notification_center.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'notification-center'}, {'phase': 1780, 'title': 'Settings and permissions UI', 'name': 'settings_and_permissions_ui', 'filename': 'settings_and_permissions_ui.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'settings-and-permissions-ui'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
