from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/destiny_flourishing")
PHASE_CONFIGS = [{'phase': 2381, 'title': 'Adaptive awareness-coordination framework', 'name': 'adaptive_awareness_coordination_framework', 'filename': 'adaptive_awareness_coordination_framework.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'adaptive-awareness-coordination-framework'}, {'phase': 2382, 'title': 'Autonomous sentience-harmonization AI', 'name': 'autonomous_sentience_harmonization_ai', 'filename': 'autonomous_sentience_harmonization_ai.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'autonomous-sentience-harmonization-ai'}, {'phase': 2383, 'title': 'Infinite-scale cognition engine', 'name': 'infinite_scale_cognition_engine', 'filename': 'infinite_scale_cognition_engine.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'infinite-scale-cognition-engine'}, {'phase': 2384, 'title': 'Recursive intelligence framework', 'name': 'recursive_intelligence_framework', 'filename': 'recursive_intelligence_framework.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'recursive-intelligence-framework'}, {'phase': 2385, 'title': 'Universal flourishing substrate', 'name': 'universal_flourishing_substrate', 'filename': 'universal_flourishing_substrate.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'universal-flourishing-substrate'}, {'phase': 2386, 'title': 'Adaptive prosperity-coordination AI', 'name': 'adaptive_prosperity_coordination_ai', 'filename': 'adaptive_prosperity_coordination_ai.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'adaptive-prosperity-coordination-ai'}, {'phase': 2387, 'title': 'Autonomous coexistence framework', 'name': 'autonomous_coexistence_framework', 'filename': 'autonomous_coexistence_framework.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'autonomous-coexistence-framework'}, {'phase': 2388, 'title': 'Infinite-scale continuity engine', 'name': 'infinite_scale_continuity_engine', 'filename': 'infinite_scale_continuity_engine.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'infinite-scale-continuity-engine'}, {'phase': 2389, 'title': 'Recursive stewardship harmonization AI', 'name': 'recursive_stewardship_harmonization_ai', 'filename': 'recursive_stewardship_harmonization_ai.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'recursive-stewardship-harmonization-ai'}, {'phase': 2390, 'title': 'Universal destiny substrate', 'name': 'universal_destiny_substrate', 'filename': 'universal_destiny_substrate.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'universal-destiny-substrate'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
