from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/document_intelligence")
PHASE_CONFIGS = [{'phase': 1851, 'title': 'Document ingestion pipeline', 'name': 'document_ingestion_pipeline', 'filename': 'document_ingestion_pipeline.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'document-ingestion-pipeline'}, {'phase': 1852, 'title': 'PDF layout reader', 'name': 'pdf_layout_reader', 'filename': 'pdf_layout_reader.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'pdf-layout-reader'}, {'phase': 1853, 'title': 'DOCX style analyzer', 'name': 'docx_style_analyzer', 'filename': 'docx_style_analyzer.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'docx-style-analyzer'}, {'phase': 1854, 'title': 'Spreadsheet formula auditor', 'name': 'spreadsheet_formula_auditor', 'filename': 'spreadsheet_formula_auditor.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'spreadsheet-formula-auditor'}, {'phase': 1855, 'title': 'CSV cleaner', 'name': 'csv_cleaner', 'filename': 'csv_cleaner.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'csv-cleaner'}, {'phase': 1856, 'title': 'Data import mapper', 'name': 'data_import_mapper', 'filename': 'data_import_mapper.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'data-import-mapper'}, {'phase': 1857, 'title': 'Invoice document parser', 'name': 'invoice_document_parser', 'filename': 'invoice_document_parser.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'invoice-document-parser'}, {'phase': 1858, 'title': 'Receipt reconciliation assistant', 'name': 'receipt_reconciliation_assistant', 'filename': 'receipt_reconciliation_assistant.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'receipt-reconciliation-assistant'}, {'phase': 1859, 'title': 'Bank statement classifier', 'name': 'bank_statement_classifier', 'filename': 'bank_statement_classifier.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'bank-statement-classifier'}, {'phase': 1860, 'title': 'Report formatting engine', 'name': 'report_formatting_engine', 'filename': 'report_formatting_engine.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'report-formatting-engine'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
