from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/excellence_insight")
PHASE_CONFIGS = [{'phase': 2321, 'title': 'Adaptive aspiration framework', 'name': 'adaptive_aspiration_framework', 'filename': 'adaptive_aspiration_framework.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'adaptive-aspiration-framework'}, {'phase': 2322, 'title': 'Autonomous ambition-coordination AI', 'name': 'autonomous_ambition_coordination_ai', 'filename': 'autonomous_ambition_coordination_ai.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'autonomous-ambition-coordination-ai'}, {'phase': 2323, 'title': 'Infinite-scale achievement engine', 'name': 'infinite_scale_achievement_engine', 'filename': 'infinite_scale_achievement_engine.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'infinite-scale-achievement-engine'}, {'phase': 2324, 'title': 'Recursive mastery harmonization framework', 'name': 'recursive_mastery_harmonization_framework', 'filename': 'recursive_mastery_harmonization_framework.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'recursive-mastery-harmonization-framework'}, {'phase': 2325, 'title': 'Universal excellence substrate', 'name': 'universal_excellence_substrate', 'filename': 'universal_excellence_substrate.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'universal-excellence-substrate'}, {'phase': 2326, 'title': 'Adaptive leadership-coordination AI', 'name': 'adaptive_leadership_coordination_ai', 'filename': 'adaptive_leadership_coordination_ai.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'adaptive-leadership-coordination-ai'}, {'phase': 2327, 'title': 'Autonomous mentorship framework', 'name': 'autonomous_mentorship_framework', 'filename': 'autonomous_mentorship_framework.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'autonomous-mentorship-framework'}, {'phase': 2328, 'title': 'Infinite-scale guidance engine', 'name': 'infinite_scale_guidance_engine', 'filename': 'infinite_scale_guidance_engine.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'infinite-scale-guidance-engine'}, {'phase': 2329, 'title': 'Recursive wisdom harmonization AI', 'name': 'recursive_wisdom_harmonization_ai', 'filename': 'recursive_wisdom_harmonization_ai.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'recursive-wisdom-harmonization-ai'}, {'phase': 2330, 'title': 'Universal insight substrate', 'name': 'universal_insight_substrate', 'filename': 'universal_insight_substrate.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'universal-insight-substrate'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
