from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/existential_continuity")
PHASE_CONFIGS = [{'phase': 2351, 'title': 'Adaptive existential framework', 'name': 'adaptive_existential_framework', 'filename': 'adaptive_existential_framework.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'adaptive-existential-framework'}, {'phase': 2352, 'title': 'Autonomous philosophical-coordination AI', 'name': 'autonomous_philosophical_coordination_ai', 'filename': 'autonomous_philosophical_coordination_ai.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'autonomous-philosophical-coordination-ai'}, {'phase': 2353, 'title': 'Infinite-scale meaning harmonization engine', 'name': 'infinite_scale_meaning_harmonization_engine', 'filename': 'infinite_scale_meaning_harmonization_engine.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'infinite-scale-meaning-harmonization-engine'}, {'phase': 2354, 'title': 'Recursive purpose framework', 'name': 'recursive_purpose_framework', 'filename': 'recursive_purpose_framework.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'recursive-purpose-framework'}, {'phase': 2355, 'title': 'Universal fulfillment substrate', 'name': 'universal_fulfillment_substrate', 'filename': 'universal_fulfillment_substrate.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'universal-fulfillment-substrate'}, {'phase': 2356, 'title': 'Adaptive destiny-coordination AI', 'name': 'adaptive_destiny_coordination_ai', 'filename': 'adaptive_destiny_coordination_ai.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'adaptive-destiny-coordination-ai'}, {'phase': 2357, 'title': 'Autonomous flourishing framework', 'name': 'autonomous_flourishing_framework', 'filename': 'autonomous_flourishing_framework.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'autonomous-flourishing-framework'}, {'phase': 2358, 'title': 'Infinite-scale harmony engine', 'name': 'infinite_scale_harmony_engine', 'filename': 'infinite_scale_harmony_engine.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'infinite-scale-harmony-engine'}, {'phase': 2359, 'title': 'Recursive coexistence harmonization AI', 'name': 'recursive_coexistence_harmonization_ai', 'filename': 'recursive_coexistence_harmonization_ai.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'recursive-coexistence-harmonization-ai'}, {'phase': 2360, 'title': 'Universal continuity substrate', 'name': 'universal_continuity_substrate', 'filename': 'universal_continuity_substrate.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'universal-continuity-substrate'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
