from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/github_productivity")
PHASE_CONFIGS = [{'phase': 1811, 'title': 'Form automation agent', 'name': 'form_automation_agent', 'filename': 'form_automation_agent.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'form-automation-agent'}, {'phase': 1812, 'title': 'Web dashboard operator', 'name': 'web_dashboard_operator', 'filename': 'web_dashboard_operator.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'web-dashboard-operator'}, {'phase': 1813, 'title': 'Analytics dashboard reader', 'name': 'analytics_dashboard_reader', 'filename': 'analytics_dashboard_reader.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'analytics-dashboard-reader'}, {'phase': 1814, 'title': 'Hosting panel assistant', 'name': 'hosting_panel_assistant', 'filename': 'hosting_panel_assistant.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'hosting-panel-assistant'}, {'phase': 1815, 'title': 'cPanel workflow helper', 'name': 'cpanel_workflow_helper', 'filename': 'cpanel_workflow_helper.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'cpanel-workflow-helper'}, {'phase': 1816, 'title': 'phpMyAdmin assistant', 'name': 'phpmyadmin_assistant', 'filename': 'phpmyadmin_assistant.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'phpmyadmin-assistant'}, {'phase': 1817, 'title': 'GitHub workflow operator', 'name': 'github_workflow_operator', 'filename': 'github_workflow_operator.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'github-workflow-operator'}, {'phase': 1818, 'title': 'Issue-to-branch planner', 'name': 'issue_to_branch_planner', 'filename': 'issue_to_branch_planner.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'issue-to-branch-planner'}, {'phase': 1819, 'title': 'Pull request reviewer', 'name': 'pull_request_reviewer', 'filename': 'pull_request_reviewer.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'pull-request-reviewer'}, {'phase': 1820, 'title': 'Commit message generator', 'name': 'commit_message_generator', 'filename': 'commit_message_generator.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'commit-message-generator'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
