from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/metacognition_transcendence")
PHASE_CONFIGS = [{'phase': 2341, 'title': 'Adaptive experiential framework', 'name': 'adaptive_experiential_framework', 'filename': 'adaptive_experiential_framework.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'adaptive-experiential-framework'}, {'phase': 2342, 'title': 'Autonomous immersion-coordination AI', 'name': 'autonomous_immersion_coordination_ai', 'filename': 'autonomous_immersion_coordination_ai.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'autonomous-immersion-coordination-ai'}, {'phase': 2343, 'title': 'Infinite-scale simulation harmonization engine', 'name': 'infinite_scale_simulation_harmonization_engine', 'filename': 'infinite_scale_simulation_harmonization_engine.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'infinite-scale-simulation-harmonization-engine'}, {'phase': 2344, 'title': 'Recursive reality framework', 'name': 'recursive_reality_framework', 'filename': 'recursive_reality_framework.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'recursive-reality-framework'}, {'phase': 2345, 'title': 'Universal metacognition substrate', 'name': 'universal_metacognition_substrate', 'filename': 'universal_metacognition_substrate.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'universal-metacognition-substrate'}, {'phase': 2346, 'title': 'Adaptive self-reflection AI', 'name': 'adaptive_self_reflection_ai', 'filename': 'adaptive_self_reflection_ai.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'adaptive-self-reflection-ai'}, {'phase': 2347, 'title': 'Autonomous introspection framework', 'name': 'autonomous_introspection_framework', 'filename': 'autonomous_introspection_framework.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'autonomous-introspection-framework'}, {'phase': 2348, 'title': 'Infinite-scale awareness engine', 'name': 'infinite_scale_awareness_engine', 'filename': 'infinite_scale_awareness_engine.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'infinite-scale-awareness-engine'}, {'phase': 2349, 'title': 'Recursive consciousness harmonization AI', 'name': 'recursive_consciousness_harmonization_ai', 'filename': 'recursive_consciousness_harmonization_ai.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'recursive-consciousness-harmonization-ai'}, {'phase': 2350, 'title': 'Universal transcendence substrate', 'name': 'universal_transcendence_substrate', 'filename': 'universal_transcendence_substrate.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'universal-transcendence-substrate'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
