from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/multilingual_voice_workflow")
PHASE_CONFIGS = [{'phase': 1761, 'title': 'Offline voice personalization', 'name': 'offline_voice_personalization', 'filename': 'offline_voice_personalization.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'offline-voice-personalization'}, {'phase': 1762, 'title': 'Multilingual Tamil-English support', 'name': 'multilingual_tamil_english_support', 'filename': 'multilingual_tamil_english_support.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'multilingual-tamil-english-support'}, {'phase': 1763, 'title': 'Sinhala support layer', 'name': 'sinhala_support_layer', 'filename': 'sinhala_support_layer.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'sinhala-support-layer'}, {'phase': 1764, 'title': 'Accent adaptation for Sri Lanka', 'name': 'accent_adaptation_for_sri_lanka', 'filename': 'accent_adaptation_for_sri_lanka.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'accent-adaptation-for-sri-lanka'}, {'phase': 1765, 'title': 'Voice shortcut macros', 'name': 'voice_shortcut_macros', 'filename': 'voice_shortcut_macros.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'voice-shortcut-macros'}, {'phase': 1766, 'title': 'Hands-free coding assistant', 'name': 'hands_free_coding_assistant', 'filename': 'hands_free_coding_assistant.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'hands-free-coding-assistant'}, {'phase': 1767, 'title': 'Voice-driven terminal planner', 'name': 'voice_driven_terminal_planner', 'filename': 'voice_driven_terminal_planner.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'voice-driven-terminal-planner'}, {'phase': 1768, 'title': 'Voice-safe command approval', 'name': 'voice_safe_command_approval', 'filename': 'voice_safe_command_approval.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'voice-safe-command-approval'}, {'phase': 1769, 'title': 'Voice note capture', 'name': 'voice_note_capture', 'filename': 'voice_note_capture.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'voice-note-capture'}, {'phase': 1770, 'title': 'Voice-to-task conversion', 'name': 'voice_to_task_conversion', 'filename': 'voice_to_task_conversion.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'voice-to-task-conversion'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
