from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/personal_life_management")
PHASE_CONFIGS = [{'phase': 1891, 'title': 'Spiritual routine reminder', 'name': 'spiritual_routine_reminder', 'filename': 'spiritual_routine_reminder.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'spiritual-routine-reminder'}, {'phase': 1892, 'title': 'Wedding budget planner', 'name': 'wedding_budget_planner', 'filename': 'wedding_budget_planner.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'wedding-budget-planner'}, {'phase': 1893, 'title': 'Family event planner', 'name': 'family_event_planner', 'filename': 'family_event_planner.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'family-event-planner'}, {'phase': 1894, 'title': 'Personal finance tracker', 'name': 'personal_finance_tracker', 'filename': 'personal_finance_tracker.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'personal-finance-tracker'}, {'phase': 1895, 'title': 'Savings goal simulator', 'name': 'savings_goal_simulator', 'filename': 'savings_goal_simulator.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'savings-goal-simulator'}, {'phase': 1896, 'title': 'Asset planning assistant', 'name': 'asset_planning_assistant', 'filename': 'asset_planning_assistant.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'asset-planning-assistant'}, {'phase': 1897, 'title': 'Life operating dashboard', 'name': 'life_operating_dashboard', 'filename': 'life_operating_dashboard.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'life-operating-dashboard'}, {'phase': 1898, 'title': 'Personal decision journal', 'name': 'personal_decision_journal', 'filename': 'personal_decision_journal.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'personal-decision-journal'}, {'phase': 1899, 'title': 'Daily command briefing', 'name': 'daily_command_briefing', 'filename': 'daily_command_briefing.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'daily-command-briefing'}, {'phase': 1900, 'title': 'Janon personal command center', 'name': 'janon_personal_command_center', 'filename': 'janon_personal_command_center.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'janon-personal-command-center'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
