from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/personal_wellness")
PHASE_CONFIGS = [{'phase': 1881, 'title': 'Health and fitness planner', 'name': 'health_and_fitness_planner', 'filename': 'health_and_fitness_planner.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'health-and-fitness-planner'}, {'phase': 1882, 'title': 'Habit accountability engine', 'name': 'habit_accountability_engine', 'filename': 'habit_accountability_engine.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'habit-accountability-engine'}, {'phase': 1883, 'title': 'Smoking reduction tracker', 'name': 'smoking_reduction_tracker', 'filename': 'smoking_reduction_tracker.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'smoking-reduction-tracker'}, {'phase': 1884, 'title': 'Hydration safety reminder', 'name': 'hydration_safety_reminder', 'filename': 'hydration_safety_reminder.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'hydration-safety-reminder'}, {'phase': 1885, 'title': 'Workout injury-risk checker', 'name': 'workout_injury_risk_checker', 'filename': 'workout_injury_risk_checker.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'workout-injury-risk-checker'}, {'phase': 1886, 'title': 'Meal preference memory', 'name': 'meal_preference_memory', 'filename': 'meal_preference_memory.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'meal-preference-memory'}, {'phase': 1887, 'title': 'Weight-loss progress dashboard', 'name': 'weight_loss_progress_dashboard', 'filename': 'weight_loss_progress_dashboard.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'weight-loss-progress-dashboard'}, {'phase': 1888, 'title': 'Sleep routine assistant', 'name': 'sleep_routine_assistant', 'filename': 'sleep_routine_assistant.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'sleep-routine-assistant'}, {'phase': 1889, 'title': 'Stress workload balancer', 'name': 'stress_workload_balancer', 'filename': 'stress_workload_balancer.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'stress-workload-balancer'}, {'phase': 1890, 'title': 'Personal calendar health guard', 'name': 'personal_calendar_health_guard', 'filename': 'personal_calendar_health_guard.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'personal-calendar-health-guard'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
