from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/platform_connector")
PHASE_CONFIGS = [{'phase': 1971, 'title': 'SMS gateway connector', 'name': 'sms_gateway_connector', 'filename': 'sms_gateway_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'sms-gateway-connector'}, {'phase': 1972, 'title': 'Email marketing connector', 'name': 'email_marketing_connector', 'filename': 'email_marketing_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'email-marketing-connector'}, {'phase': 1973, 'title': 'CRM connector', 'name': 'crm_connector', 'filename': 'crm_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'crm-connector'}, {'phase': 1974, 'title': 'Analytics connector', 'name': 'analytics_connector', 'filename': 'analytics_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'analytics-connector'}, {'phase': 1975, 'title': 'Search Console connector', 'name': 'search_console_connector', 'filename': 'search_console_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'search-console-connector'}, {'phase': 1976, 'title': 'Ads manager connector', 'name': 'ads_manager_connector', 'filename': 'ads_manager_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'ads-manager-connector'}, {'phase': 1977, 'title': 'Cloud hosting connector', 'name': 'cloud_hosting_connector', 'filename': 'cloud_hosting_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'cloud-hosting-connector'}, {'phase': 1978, 'title': 'GitHub connector', 'name': 'github_connector', 'filename': 'github_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'github-connector'}, {'phase': 1979, 'title': 'GitLab connector', 'name': 'gitlab_connector', 'filename': 'gitlab_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'gitlab-connector'}, {'phase': 1980, 'title': 'Bitbucket connector', 'name': 'bitbucket_connector', 'filename': 'bitbucket_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'bitbucket-connector'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
