from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/productivity_connector")
PHASE_CONFIGS = [{'phase': 1981, 'title': 'Slack connector', 'name': 'slack_connector', 'filename': 'slack_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'slack-connector'}, {'phase': 1982, 'title': 'Discord connector', 'name': 'discord_connector', 'filename': 'discord_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'discord-connector'}, {'phase': 1983, 'title': 'Telegram connector', 'name': 'telegram_connector', 'filename': 'telegram_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'telegram-connector'}, {'phase': 1984, 'title': 'Notion connector', 'name': 'notion_connector', 'filename': 'notion_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'notion-connector'}, {'phase': 1985, 'title': 'Google Drive connector', 'name': 'google_drive_connector', 'filename': 'google_drive_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'google-drive-connector'}, {'phase': 1986, 'title': 'Microsoft 365 connector', 'name': 'microsoft_365_connector', 'filename': 'microsoft_365_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'microsoft-365-connector'}, {'phase': 1987, 'title': 'Local filesystem connector', 'name': 'local_filesystem_connector', 'filename': 'local_filesystem_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'local-filesystem-connector'}, {'phase': 1988, 'title': 'Database connector', 'name': 'database_connector', 'filename': 'database_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'database-connector'}, {'phase': 1989, 'title': 'API connector builder', 'name': 'api_connector_builder', 'filename': 'api_connector_builder.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'api-connector-builder'}, {'phase': 1990, 'title': 'OAuth connector manager', 'name': 'oauth_connector_manager', 'filename': 'oauth_connector_manager.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'oauth-connector-manager'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
