from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/release_migration")
PHASE_CONFIGS = [{'phase': 1821, 'title': 'Release note generator', 'name': 'release_note_generator', 'filename': 'release_note_generator.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'release-note-generator'}, {'phase': 1822, 'title': 'Changelog intelligence', 'name': 'changelog_intelligence', 'filename': 'changelog_intelligence.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'changelog-intelligence'}, {'phase': 1823, 'title': 'Versioning advisor', 'name': 'versioning_advisor', 'filename': 'versioning_advisor.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'versioning-advisor'}, {'phase': 1824, 'title': 'Semantic-release planner', 'name': 'semantic_release_planner', 'filename': 'semantic_release_planner.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'semantic-release-planner'}, {'phase': 1825, 'title': 'Dependency update PR assistant', 'name': 'dependency_update_pr_assistant', 'filename': 'dependency_update_pr_assistant.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'dependency-update-pr-assistant'}, {'phase': 1826, 'title': 'Codebase migration planner', 'name': 'codebase_migration_planner', 'filename': 'codebase_migration_planner.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'codebase-migration-planner'}, {'phase': 1827, 'title': 'Laravel version upgrade assistant', 'name': 'laravel_version_upgrade_assistant', 'filename': 'laravel_version_upgrade_assistant.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'laravel-version-upgrade-assistant'}, {'phase': 1828, 'title': 'PHP version upgrade checker', 'name': 'php_version_upgrade_checker', 'filename': 'php_version_upgrade_checker.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'php-version-upgrade-checker'}, {'phase': 1829, 'title': 'Node version upgrade checker', 'name': 'node_version_upgrade_checker', 'filename': 'node_version_upgrade_checker.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'node-version-upgrade-checker'}, {'phase': 1830, 'title': 'Frontend framework migration advisor', 'name': 'frontend_framework_migration_advisor', 'filename': 'frontend_framework_migration_advisor.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'frontend-framework-migration-advisor'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
