from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/saas_commercialization")
PHASE_CONFIGS = [{'phase': 1941, 'title': 'SaaS packaging strategy', 'name': 'saas_packaging_strategy', 'filename': 'saas_packaging_strategy.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'saas-packaging-strategy'}, {'phase': 1942, 'title': 'License activation system', 'name': 'license_activation_system', 'filename': 'license_activation_system.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'license-activation-system'}, {'phase': 1943, 'title': 'Subscription billing gateway', 'name': 'subscription_billing_gateway', 'filename': 'subscription_billing_gateway.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'subscription-billing-gateway'}, {'phase': 1944, 'title': 'Trial and onboarding flow', 'name': 'trial_and_onboarding_flow', 'filename': 'trial_and_onboarding_flow.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'trial-and-onboarding-flow'}, {'phase': 1945, 'title': 'Tenant admin dashboard', 'name': 'tenant_admin_dashboard', 'filename': 'tenant_admin_dashboard.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'tenant-admin-dashboard'}, {'phase': 1946, 'title': 'Customer support portal', 'name': 'customer_support_portal', 'filename': 'customer_support_portal.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'customer-support-portal'}, {'phase': 1947, 'title': 'Documentation site', 'name': 'documentation_site', 'filename': 'documentation_site.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'documentation-site'}, {'phase': 1948, 'title': 'Developer API portal', 'name': 'developer_api_portal', 'filename': 'developer_api_portal.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'developer-api-portal'}, {'phase': 1949, 'title': 'Extension marketplace', 'name': 'extension_marketplace', 'filename': 'extension_marketplace.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'extension-marketplace'}, {'phase': 1950, 'title': 'Plugin SDK', 'name': 'plugin_sdk', 'filename': 'plugin_sdk.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'plugin-sdk'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
