from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/screen_automation")
PHASE_CONFIGS = [{'phase': 1801, 'title': 'Screen understanding layer', 'name': 'screen_understanding_layer', 'filename': 'screen_understanding_layer.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'screen-understanding-layer'}, {'phase': 1802, 'title': 'Screenshot-to-action planner', 'name': 'screenshot_to_action_planner', 'filename': 'screenshot_to_action_planner.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'screenshot-to-action-planner'}, {'phase': 1803, 'title': 'UI element detector', 'name': 'ui_element_detector', 'filename': 'ui_element_detector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'ui-element-detector'}, {'phase': 1804, 'title': 'Desktop click automation', 'name': 'desktop_click_automation', 'filename': 'desktop_click_automation.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'desktop-click-automation'}, {'phase': 1805, 'title': 'Keyboard macro automation', 'name': 'keyboard_macro_automation', 'filename': 'keyboard_macro_automation.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'keyboard-macro-automation'}, {'phase': 1806, 'title': 'Window focus manager', 'name': 'window_focus_manager', 'filename': 'window_focus_manager.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'window-focus-manager'}, {'phase': 1807, 'title': 'App state recognizer', 'name': 'app_state_recognizer', 'filename': 'app_state_recognizer.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'app-state-recognizer'}, {'phase': 1808, 'title': 'VS Code assistant bridge', 'name': 'vs_code_assistant_bridge', 'filename': 'vs_code_assistant_bridge.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'vs-code-assistant-bridge'}, {'phase': 1809, 'title': 'Terminal session reader', 'name': 'terminal_session_reader', 'filename': 'terminal_session_reader.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'terminal-session-reader'}, {'phase': 1810, 'title': 'Browser tab manager', 'name': 'browser_tab_manager', 'filename': 'browser_tab_manager.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'browser-tab-manager'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
