from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/sync_control_network")
PHASE_CONFIGS = [{'phase': 1791, 'title': 'Remote file viewer', 'name': 'remote_file_viewer', 'filename': 'remote_file_viewer.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'remote-file-viewer'}, {'phase': 1792, 'title': 'Remote project diagnostics', 'name': 'remote_project_diagnostics', 'filename': 'remote_project_diagnostics.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'remote-project-diagnostics'}, {'phase': 1793, 'title': 'Remote voice command gateway', 'name': 'remote_voice_command_gateway', 'filename': 'remote_voice_command_gateway.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'remote-voice-command-gateway'}, {'phase': 1794, 'title': 'Mobile notification bridge', 'name': 'mobile_notification_bridge', 'filename': 'mobile_notification_bridge.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'mobile-notification-bridge'}, {'phase': 1795, 'title': 'Offline sync queue', 'name': 'offline_sync_queue', 'filename': 'offline_sync_queue.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'offline-sync-queue'}, {'phase': 1796, 'title': 'Conflict-safe sync engine', 'name': 'conflict_safe_sync_engine', 'filename': 'conflict_safe_sync_engine.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'conflict-safe-sync-engine'}, {'phase': 1797, 'title': 'Encrypted device-to-device memory', 'name': 'encrypted_device_to_device_memory', 'filename': 'encrypted_device_to_device_memory.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'encrypted-device-to-device-memory'}, {'phase': 1798, 'title': 'Personal cloud relay', 'name': 'personal_cloud_relay', 'filename': 'personal_cloud_relay.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'personal-cloud-relay'}, {'phase': 1799, 'title': 'Self-hosted control panel', 'name': 'self_hosted_control_panel', 'filename': 'self_hosted_control_panel.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'self-hosted-control-panel'}, {'phase': 1800, 'title': 'Sovereign AI control network', 'name': 'sovereign_ai_control_network', 'filename': 'sovereign_ai_control_network.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'sovereign-ai-control-network'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
