from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/ux_product_strategy")
PHASE_CONFIGS = [{'phase': 1841, 'title': 'UX heuristic evaluator', 'name': 'ux_heuristic_evaluator', 'filename': 'ux_heuristic_evaluator.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'ux-heuristic-evaluator'}, {'phase': 1842, 'title': 'User persona simulator', 'name': 'user_persona_simulator', 'filename': 'user_persona_simulator.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'user-persona-simulator'}, {'phase': 1843, 'title': 'Customer journey mapper', 'name': 'customer_journey_mapper', 'filename': 'customer_journey_mapper.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'customer-journey-mapper'}, {'phase': 1844, 'title': 'Wireframe generator', 'name': 'wireframe_generator', 'filename': 'wireframe_generator.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'wireframe-generator'}, {'phase': 1845, 'title': 'Prototype review assistant', 'name': 'prototype_review_assistant', 'filename': 'prototype_review_assistant.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'prototype-review-assistant'}, {'phase': 1846, 'title': 'Conversion-focused layout planner', 'name': 'conversion_focused_layout_planner', 'filename': 'conversion_focused_layout_planner.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'conversion-focused-layout-planner'}, {'phase': 1847, 'title': 'Mobile app UI strategist', 'name': 'mobile_app_ui_strategist', 'filename': 'mobile_app_ui_strategist.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'mobile-app-ui-strategist'}, {'phase': 1848, 'title': 'Admin dashboard UX architect', 'name': 'admin_dashboard_ux_architect', 'filename': 'admin_dashboard_ux_architect.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'admin-dashboard-ux-architect'}, {'phase': 1849, 'title': 'POS interface optimization AI', 'name': 'pos_interface_optimization_ai', 'filename': 'pos_interface_optimization_ai.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'pos-interface-optimization-ai'}, {'phase': 1850, 'title': 'Enterprise UI governance', 'name': 'enterprise_ui_governance', 'filename': 'enterprise_ui_governance.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'enterprise-ui-governance'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
