from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/voice_interaction")
PHASE_CONFIGS = [{'phase': 1751, 'title': 'Voice wake-word refinement', 'name': 'voice_wake_word_refinement', 'filename': 'voice_wake_word_refinement.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'voice-wake-word-refinement'}, {'phase': 1752, 'title': 'Voice command grammar', 'name': 'voice_command_grammar', 'filename': 'voice_command_grammar.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'voice-command-grammar'}, {'phase': 1753, 'title': 'Noisy-room transcription filter', 'name': 'noisy_room_transcription_filter', 'filename': 'noisy_room_transcription_filter.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'noisy-room-transcription-filter'}, {'phase': 1754, 'title': 'Speaker diarization', 'name': 'speaker_diarization', 'filename': 'speaker_diarization.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'speaker-diarization'}, {'phase': 1755, 'title': 'Multi-speaker meeting mode', 'name': 'multi_speaker_meeting_mode', 'filename': 'multi_speaker_meeting_mode.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'multi-speaker-meeting-mode'}, {'phase': 1756, 'title': 'Voice emotion detection', 'name': 'voice_emotion_detection', 'filename': 'voice_emotion_detection.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'voice-emotion-detection'}, {'phase': 1757, 'title': 'Tone-aware response engine', 'name': 'tone_aware_response_engine', 'filename': 'tone_aware_response_engine.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'tone-aware-response-engine'}, {'phase': 1758, 'title': 'Command confirmation policy', 'name': 'command_confirmation_policy', 'filename': 'command_confirmation_policy.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'command-confirmation-policy'}, {'phase': 1759, 'title': 'Interruptible speech output', 'name': 'interruptible_speech_output', 'filename': 'interruptible_speech_output.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'interruptible-speech-output'}, {'phase': 1760, 'title': 'Real-time conversation memory', 'name': 'real_time_conversation_memory', 'filename': 'real_time_conversation_memory.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'real-time-conversation-memory'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
