from __future__ import annotations

from pathlib import Path

from tools.phase_summary_helper import build_phase_module


MODULE_DIR = Path("storage/workflow_connector_foundation")
PHASE_CONFIGS = [{'phase': 1951, 'title': 'Third-party connector system', 'name': 'third_party_connector_system', 'filename': 'third_party_connector_system.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'third-party-connector-system'}, {'phase': 1952, 'title': 'Zapier-style workflow builder', 'name': 'zapier_style_workflow_builder', 'filename': 'zapier_style_workflow_builder.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'zapier-style-workflow-builder'}, {'phase': 1953, 'title': 'Visual automation builder', 'name': 'visual_automation_builder', 'filename': 'visual_automation_builder.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'visual-automation-builder'}, {'phase': 1954, 'title': 'Trigger-action rule engine', 'name': 'trigger_action_rule_engine', 'filename': 'trigger_action_rule_engine.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'trigger-action-rule-engine'}, {'phase': 1955, 'title': 'Scheduled automation engine', 'name': 'scheduled_automation_engine', 'filename': 'scheduled_automation_engine.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'scheduled-automation-engine'}, {'phase': 1956, 'title': 'Conditional watcher engine', 'name': 'conditional_watcher_engine', 'filename': 'conditional_watcher_engine.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'conditional-watcher-engine'}, {'phase': 1957, 'title': 'Notification routing engine', 'name': 'notification_routing_engine', 'filename': 'notification_routing_engine.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'notification-routing-engine'}, {'phase': 1958, 'title': 'Multi-channel messaging bridge', 'name': 'multi_channel_messaging_bridge', 'filename': 'multi_channel_messaging_bridge.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'multi-channel-messaging-bridge'}, {'phase': 1959, 'title': 'WhatsApp business connector', 'name': 'whatsapp_business_connector', 'filename': 'whatsapp_business_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'whatsapp-business-connector'}, {'phase': 1960, 'title': 'Facebook connector', 'name': 'facebook_connector', 'filename': 'facebook_connector.json', 'collection_key': 'records', 'healthy_flag': 'healthy', 'attention_flag': 'attention', 'mode': 'facebook-connector'}]
PHASE_ROUTES = build_phase_module(globals(), "MODULE_DIR", PHASE_CONFIGS)
